// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":true,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"Blackeryu_DataManager","status":false,"description":"","parameters":{}},
{"name":"Blackeryu_MenuTest","status":false,"description":"","parameters":{}},
{"name":"Blackeryu_window","status":false,"description":"","parameters":{}},
{"name":"EnemyBook","status":true,"description":"Displays detailed statuses of enemies.","parameters":{"Unknown Data":"??????"}},
{"name":"RS_Window_KorNameEdit","status":true,"description":"This plugin provides a keyboard that allows\r\n\r\nyou to type in korean or other native language in the Name Input Proccessing","parameters":{"windowWidth":"580","windowCenter":"false","editWindow_Opacity":"225","askingText":"Please enter the name","outlineWidth":"1","outlineColor":"black","fontColor":"white","standardFontSize":"28"}}
];
